### ISSUE TITLE
Windows: using DOS command line arguments is not possible

### ISSUE THREAD

**Issue by MrGung** [babashka/process#32]
Seems there is a problem with slashes (as used in most dos-tools for command line arguments/switches).

I.e.

`(println (-> (process '[dir "/S" "/OD" "/B" "/AD"]) :out slurp))`

prints nothing. Whereas

`(println (-> (process '[dir /S /OD /B /AD]) :out slurp))`

gives 

```
Type:     clojure.lang.ExceptionInfo
Message:  [line 5, col 31] Invalid symbol: /S.
Location: c:\ProgramData\DATEV\LOG\Install\VAA1DAV0171\openMostCurrentDir.clj:5:
Phase:    parse

Exception in thread "main" java.lang.NullPointerException
        at clojure.lang.Numbers.ops(Numbers.java:1068)
        at clojure.lang.Numbers.dec(Numbers.java:145)
        at babashka.impl.error_handler$error_context.invokeStatic(error_handler.clj:51)
        at babashka.impl.error_handler$error_handler.invokeStatic(error_handler.clj:106)
        at babashka.main$main$fn__18864.invoke(main.clj:625)
        at babashka.main$main.invokeStatic(main.clj:599)
        at babashka.main$main.doInvoke(main.clj:462)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at babashka.main$_main.invokeStatic(main.clj:651)
        at babashka.main$_main.doInvoke(main.clj:645)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at babashka.main.main(Unknown Source)
```

Any way to geht this working?

**Comment by borkdude** [comment]
@MrGung Can you try:

```
(println (-> (process '[dir "/S" "/OD" "/B" "/AD"] {:escape identity}) :out slurp))
```

Babashka.process escapes arguments in a certain way on Windows to avoid common problems with invalid JSON, but this might be causing a problem in this case.

**Comment by borkdude** [comment]
@MrGung Apparently `dir` is not a standalone program in Windows, so you have to invoke it with `cmd.exe`:

```
(println (-> (process ["cmd.exe" "/C" "dir" "/S" "/OD" "/B" "/AD"]) :out slurp))
```
