### ISSUE TITLE
exception in clojure.pprint for `check` with failed process

### ISSUE THREAD

**Issue by mk** [babashka/process#53]
repro using `clojure`
```sh
clojure -Sdeps '{:deps {babashka/process {:mvn/version "0.1.0"}}}' -M -e '(require \'[babashka.process :as p]) (-> (p/process ["cd" "nonexistentdir"]) p/check)'
```

gives me the following output & stacktrace
```
Exception in thread "main" java.lang.IllegalArgumentException: Multiple methods in multimethod 'simple-dispatch' match dispatch value: class babashka.process.Process -> interface clojure.lang.IDeref and interface clojure.lang.IPersistentMap, and neither is preferred
	at clojure.lang.MultiFn.findAndCacheBestMethod(MultiFn.java:179)
	at clojure.lang.MultiFn.getMethod(MultiFn.java:150)
	at clojure.lang.MultiFn.getFn(MultiFn.java:154)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.pprint$write_out.invokeStatic(pprint_base.clj:194)
	at clojure.pprint$pprint_map$fn__11054$fn__11056.invoke(dispatch.clj:113)
	at clojure.pprint$pprint_map$fn__11054.invoke(dispatch.clj:113)
	at clojure.pprint$pprint_map.invokeStatic(dispatch.clj:112)
	at clojure.pprint$pprint_map.invoke(dispatch.clj:106)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.pprint$write_out.invokeStatic(pprint_base.clj:194)
	at clojure.pprint$pprint_vector$fn__11039.invoke(dispatch.clj:95)
	at clojure.pprint$pprint_vector.invokeStatic(dispatch.clj:94)
	at clojure.pprint$pprint_vector.invoke(dispatch.clj:92)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.pprint$write_out.invokeStatic(pprint_base.clj:194)
	at clojure.pprint$pprint_map$fn__11054$fn__11056.invoke(dispatch.clj:113)
	at clojure.pprint$pprint_map$fn__11054.invoke(dispatch.clj:113)
	at clojure.pprint$pprint_map.invokeStatic(dispatch.clj:112)
	at clojure.pprint$pprint_map.invoke(dispatch.clj:106)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.pprint$write_out.invokeStatic(pprint_base.clj:194)
	at clojure.pprint$pprint_map$fn__11054$fn__11056.invoke(dispatch.clj:113)
	at clojure.pprint$pprint_map$fn__11054.invoke(dispatch.clj:113)
	at clojure.pprint$pprint_map.invokeStatic(dispatch.clj:112)
	at clojure.pprint$pprint_map.invoke(dispatch.clj:106)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.pprint$write_out.invokeStatic(pprint_base.clj:194)
	at clojure.pprint$pprint$fn__10295.invoke(pprint_base.clj:249)
	at clojure.pprint$pprint.invokeStatic(pprint_base.clj:248)
	at clojure.pprint$pprint.invoke(pprint_base.clj:241)
	at clojure.pprint$pprint.invokeStatic(pprint_base.clj:245)
	at clojure.pprint$pprint.invoke(pprint_base.clj:241)
	at clojure.lang.Var.invoke(Var.java:384)
	at clojure.main$report_error$fn__9184$fn__9185.invoke(main.clj:603)
	at clojure.main$report_error$fn__9184.invoke(main.clj:602)
	at clojure.main$report_error.invokeStatic(main.clj:601)
	at clojure.main$main.invokeStatic(main.clj:666)
	at clojure.main$main.doInvoke(main.clj:616)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:40)
```
Let me know if there's more info I should provide.

**Comment by borkdude** [comment]
This issue is documented here: https://github.com/babashka/process#clojurepprint

**Comment by borkdude** [comment]
Other than the workaround in the READMe, I guess we could introduce a custom pprinter in this library:

``` clojure
user=> (defmethod pprint/simple-dispatch babashka.process.Process [out] (.write *out* "foo"))
```

**Comment by shyamkovuri3** [comment]
tried both but still same error with latest bb version

(prefer-method pprint/simple-dispatch clojure.lang.IPersistentMap clojure.lang.IDeref)
(defmethod pprint/simple-dispatch babashka.process.Process [out] (.write *out* "foo"))

any other suggestions if it works for someone else?

**Comment by bobisageek** [comment]
As far as the pprinter implementation in the lib, how do you feel about basically just pprinting it as a map? I feel like this would sort of align with most records and the `print-method` impl.

**Comment by borkdude** [comment]
Agreed.
